/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Racecrazy;

public class App {

        public static void main(String[] args) {
            Veiculo fusca = new Veiculo(new MotordeFusca());
            Veiculo ferrari = new Veiculo(new MotordeFerrari());
            Veiculo lamborguini = new Veiculo(new MotorLamborguini());
            
            System.out.println(fusca.acelerar());
            System.out.println(ferrari.acelerar());
            System.out.println(lamborguini.acelerar());
            }

}
